export const form = {
	formID: 10,
	formTitle: 'Contact Me',
	emailActions: {
		'81': {
			title: '',
			key: '',
			type: 'email',
			active: '1',
			created_at: '2016-08-24 16:39:20',
			label: 'Email Confirmation 2',
			to: '{wp:user_email},{wp:user_email}',
			subject: 'This is an email action.',
			message: 'Hello, Ninja Forms!',
			objectType: 'Action',
			objectDomain: 'actions',
			editActive: '',
			conditions: {
				collapsed: '',
				process: '1',
				connector: 'all',
				when: [],
				then: [
					{
						key: '',
						trigger: '',
						value: '',
						type: 'field',
						modelType: 'then',
					},
				],
				else: [],
			},
			payment_gateways: '',
			payment_total: '',
			tag: '',
			email_subject: 'Submission Confirmation ',
			email_message: '<p>{fields_table}<br></p>',
			from_name: '',
			from_address: '',
			reply_to: '',
			email_format: 'html',
			cc: '',
			bcc: '',
			attach_csv: '',
			email_message_plain: '',
			parent_id: '10',
			drawerDisabled: '',
			value: '81',
		},
		'82': {
			title: '',
			key: '',
			type: 'email',
			active: '1',
			created_at: '2016-08-24 16:47:39',
			label: 'Email Notification 2',
			objectType: 'Action',
			objectDomain: 'actions',
			editActive: '',
			conditions: {
				collapsed: '',
				process: '1',
				connector: 'all',
				when: [
					{
						connector: 'AND',
						key: '',
						comparator: '',
						value: '',
						type: 'field',
						modelType: 'when',
					},
				],
				then: [
					{
						key: '',
						trigger: '',
						value: '',
						type: 'field',
						modelType: 'then',
					},
				],
				else: [],
			},
			payment_gateways: '',
			payment_total: '',
			tag: '',
			to: '{system:admin_email}',
			email_subject: 'New message from ',
			email_message: '<p></p>{field:textbox_1604392359527}<br>',
			from_name: '',
			from_address: '',
			reply_to: '',
			email_format: 'html',
			cc: '',
			bcc: '',
			attach_csv: '0',
			email_message_plain: '',
			parent_id: '10',
			drawerDisabled: '',
		},
	},
};

export const globalParams = {
	siteUrl: 'https://local.lndo.site',
	adminUrl: 'https://local.lndo.site/wp-admin/',
	restUrl: 'https://local.lndo.site/wp-json/',
	token: '322e7b3550',
	forms: {
		'10': {
			formID: 10,
			formTitle: 'Contact Me',
			emailActions: {
				'81': {
					title: '',
					key: '',
					type: 'email',
					active: '1',
					created_at: '2016-08-24 16:39:20',
					label: 'Email Confirmation 2',
					to: '{wp:user_email},{wp:user_email}',
					subject: 'This is an email action.',
					message: 'Hello, Ninja Forms!',
					objectType: 'Action',
					objectDomain: 'actions',
					editActive: '',
					conditions: {
						collapsed: '',
						process: '1',
						connector: 'all',
						when: [],
						then: [
							{
								key: '',
								trigger: '',
								value: '',
								type: 'field',
								modelType: 'then',
							},
						],
						else: [],
					},
					payment_gateways: '',
					payment_total: '',
					tag: '',
					email_subject: 'Submission Confirmation ',
					email_message: '<p>{fields_table}<br></p>',
					from_name: '',
					from_address: '',
					reply_to: '',
					email_format: 'html',
					cc: '',
					bcc: '',
					attach_csv: '',
					email_message_plain: '',
					parent_id: '10',
					drawerDisabled: '',
					value: '81',
				},
				'82': {
					title: '',
					key: '',
					type: 'email',
					active: '1',
					created_at: '2016-08-24 16:47:39',
					label: 'Email Notification 2',
					objectType: 'Action',
					objectDomain: 'actions',
					editActive: '',
					conditions: {
						collapsed: '',
						process: '1',
						connector: 'all',
						when: [
							{
								connector: 'AND',
								key: '',
								comparator: '',
								value: '',
								type: 'field',
								modelType: 'when',
							},
						],
						then: [
							{
								key: '',
								trigger: '',
								value: '',
								type: 'field',
								modelType: 'then',
							},
						],
						else: [],
					},
					payment_gateways: '',
					payment_total: '',
					tag: '',
					to: '{system:admin_email}',
					email_subject: 'New message from ',
					email_message: '<p></p>{field:textbox_1604392359527}<br>',
					from_name: '',
					from_address: '',
					reply_to: '',
					email_format: 'html',
					cc: '',
					bcc: '',
					attach_csv: '0',
					email_message_plain: '',
					parent_id: '10',
					drawerDisabled: '',
				},
			},
		},
		'11': {
			formID: 11,
			formTitle: 'Contact Me',
			emailActions: {
				'85': {
					title: '',
					key: '',
					type: 'email',
					active: '1',
					created_at: '2016-08-24 16:39:20',
					label: 'Email Confirmation',
					to: '{field:email}',
					subject: 'This is an email action.',
					message: 'Hello, Ninja Forms!',
					objectType: 'Action',
					objectDomain: 'actions',
					editActive: '',
					conditions: {
						collapsed: '',
						process: '1',
						connector: 'all',
						when: [],
						then: [
							{
								key: '',
								trigger: '',
								value: '',
								type: 'field',
								modelType: 'then',
							},
						],
						else: [],
					},
					payment_gateways: '',
					payment_total: '',
					tag: '',
					email_subject: 'Submission Confirmation ',
					email_message: '<p>{all_fields_table}<br></p>',
					from_name: '',
					from_address: '',
					reply_to: '',
					email_format: 'html',
					cc: '',
					bcc: '',
					attach_csv: '',
					email_message_plain: '',
					parent_id: '11',
				},
				'86': {
					title: '',
					key: '',
					type: 'email',
					active: '1',
					created_at: '2016-08-24 16:47:39',
					label: 'Email Notification',
					objectType: 'Action',
					objectDomain: 'actions',
					editActive: '',
					conditions: {
						collapsed: '',
						process: '1',
						connector: 'all',
						when: [
							{
								connector: 'AND',
								key: '',
								comparator: '',
								value: '',
								type: 'field',
								modelType: 'when',
							},
						],
						then: [
							{
								key: '',
								trigger: '',
								value: '',
								type: 'field',
								modelType: 'then',
							},
						],
						else: [],
					},
					payment_gateways: '',
					payment_total: '',
					tag: '',
					to: '{system:admin_email}',
					email_subject: 'New message from {field:name}',
					email_message:
						'<p>{field:message}</p><p>-{field:name} ( {field:email} )</p>',
					from_name: '',
					from_address: '',
					reply_to: '{field:email}',
					email_format: 'html',
					cc: '',
					bcc: '',
					attach_csv: '0',
					email_message_plain: '',
					parent_id: '11',
				},
			},
		},
		'12': {
			formID: 12,
			formTitle: 'Submission Test 4',
			emailActions: {
				'90': {
					title: '',
					key: '',
					type: 'email',
					active: '1',
					created_at: '2020-11-11 11:43:03',
					label: 'Admin Email',
					objectType: 'Action',
					objectDomain: 'actions',
					editActive: '',
					order: '2',
					conditions: {
						collapsed: '',
						process: '1',
						connector: 'all',
						when: [],
						then: [
							{
								key: '',
								trigger: '',
								value: '',
								type: 'field',
								modelType: 'then',
							},
						],
						else: [],
					},
					to: 'quay@saturdaydrive.com',
					reply_to: '',
					email_subject: 'Ninja Forms Submission',
					email_message: 'hi',
					email_message_plain: '',
					from_name: '',
					from_address: '',
					email_format: 'html',
					cc: '',
					bcc: '',
					drawerDisabled: '',
					parent_id: '12',
				},
				'91': {
					title: '',
					key: '',
					type: 'email',
					active: '1',
					created_at: '2020-11-11 11:43:04',
					label: 'Email',
					objectType: 'Action',
					objectDomain: 'actions',
					editActive: '',
					conditions: {
						collapsed: '',
						process: '1',
						connector: 'all',
						when: [],
						then: [
							{
								key: '',
								trigger: '',
								value: '',
								type: 'field',
								modelType: 'then',
							},
						],
						else: [],
					},
					to: 'quay@saturdaydrive.com',
					reply_to: '',
					email_subject: 'Ninja Forms Submission',
					email_message: 'Second email hi',
					email_message_plain: '',
					from_name: '',
					from_address: '',
					email_format: 'html',
					cc: '',
					bcc: '',
					drawerDisabled: '',
					parent_id: '12',
				},
			},
		},
	},
	timeFormat: 'H:i',
	dateFormat: 'd/m/Y',
};

export const triggerEmailActionsParams = {
	action: 'triggerEmailActions',
	title: 'Trigger Email Action Title',
};

export const bulkExportParams = {
	action: 'bulkExport',
	title: 'Bulk Export Title',
};

export const action = {
	title: '',
	key: '',
	type: 'email',
	active: '1',
	created_at: '2016-08-24 16:39:20',
	label: 'Email Confirmation 2',
	to: '{wp:user_email},{wp:user_email}',
	subject: 'This is an email action.',
	message: 'Hello, Ninja Forms!',
	objectType: 'Action',
	objectDomain: 'actions',
	editActive: '',
	conditions: {
		collapsed: '',
		process: '1',
		connector: 'all',
		when: [],
		then: [
			{
				key: '',
				trigger: '',
				value: '',
				type: 'field',
				modelType: 'then',
			},
		],
		else: [],
	},
	payment_gateways: '',
	payment_total: '',
	tag: '',
	email_subject: 'Submission Confirmation ',
	email_message: '<p>{fields_table}<br></p>',
	from_name: '',
	from_address: '',
	reply_to: '',
	email_format: 'html',
	cc: '',
	bcc: '',
	attach_csv: '',
	email_message_plain: '',
	parent_id: '10',
	drawerDisabled: '',
	value: '81',
};
